CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE testdb;

CREATE TABLE IF NOT EXISTS number_ranges (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  start_num INT NOT NULL,
  end_num INT NOT NULL,
  numbers TEXT NOT NULL,
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;